### ISSUE TITLE
Package does not contain merkletools.py

### ISSUE THREAD

**Issue by lontivero** [Tierion/pymerkletools#1]
@EderSantana the package [merkletools-1.0.0.tar.gz](https://pypi.python.org/pypi/merkletools) does not contain the merkletools.py file.

**Comment by EderSantana** [comment]
@lontivero thanks for letting me know. I'll check why that happened. Meanwhile, please install with `pip install merkletools` and let me know if that works ok for you.

**Comment by lontivero** [comment]
i did ```pip install merkletools``` many times (in both windows and linux) and that installed the merkletools package and its dependency sha3 successfully. However, given the merkletools.py file is not included in the package, i couldn't use it.

Anyway, i've moved my programming environment to linux (sha3 doesn't compile in windows, or at least in my windows) and i've downloaded the merkletools.py file in my own package adn it works okay by the moment.

**Comment by EderSantana** [comment]
I understand now, tkx for the detailed report. I'll patch a fix soon.

**Comment by lontivero** [comment]
I'm not a python programmer but i had the same problem a minute ago and the solution that I found was including my .py files in the <package-name>.egg-info/SOURCES.txt file

**Comment by EderSantana** [comment]
yeah, I solved that by creating a MANIFEST.in file: https://github.com/Tierion/pymerkletools/commit/4dcf67ec9ac419abf9b1d430608bee680d317844

Checkout the new download, it has the files now: https://pypi.python.org/pypi?:action=display&name=merkletools&version=1.0.1

Let me know if something is still missing.

**Comment by EderSantana** [comment]
actually, give me one second, there are a few things missing. brb

**Comment by EderSantana** [comment]
here is the current module https://pypi.python.org/pypi/merkletools/1.0.2
pypi requires the module to be inside a folder with the name of the project. I hate unnecessary folders, but rules are rules :D

**Comment by lontivero** [comment]
It works okay now! Thank you, @EderSantana
