### ISSUE TITLE
Question: Merkle-Trees

### ISSUE THREAD

**Issue by hheile** [Tierion/pymerkletools#2]
Hello, 
just came across your github while trying to implement a merkle-tree and hope you can help me get on the right track.

here is the tree how it SHOULD look like

                                                                           ROOT
                                                    F                                                  F
                                       F                         F                       71                        F
                             13             80         54       38            99       27           65    87

i have no idea how the get the 71 from the 99 and the 27.
i need to calculate the root only from this nowing decimals. i believe the final thing is a SHA256 hash, but i'm not pretty sure. 

so whats next, i'm  trying to build an implemention (based on yours) with the following features:
1) set the level of deep for the tree, for my example its 4 levels, with same number of leaves of each site (no uplifting)

2) select the hashing (MD5, SHA1, SHA256, whatever)

3) input the base data (for me its 13,80 for the first, 54,48 for the second, 99,27 for the third, 65,87 for the last. 

3) calculate the tree

if you have any snippets for that it would help me really. 
thanks in advance

hheileeeee

**Comment by grempe** [comment]
Hi.

If you are looking for general info about Merkle trees and how they are constructed I might recommend:

- https://en.wikipedia.org/wiki/Merkle_tree
- http://www.emsec.rub.de/media/crypto/attachments/files/2011/04/becker_1.pdf
- https://brilliant.org/wiki/merkle-tree/

And of course our own merkle-tools implementation in Javascript might help.

https://github.com/tierion/merkle-tools

Thanks for reaching out and I hope you find those links helpful. I will close this as there doesn't seem to be a question or issue with this implementation.
